server:
  port: 5566
  
  thymeleaf:
    cache: false # \u5F00\u53D1\u65F6\u5173\u95ED\u7F13\u5B58,\u4E0D\u7136\u6CA1\u6CD5\u770B\u5230\u5B9E\u65F6\u9875\u9762
    mode: LEGACYHTML5 # \u7528\u975E\u4E25\u683C\u7684 HTML
    encoding: UTF-8
#    prefix: classpath:/templates/
    servlet:
      content-type: text/html